@echo off
setlocal
echo ---------------------------------------------------
echo KitokoCSS CLI Installer for Windows
echo ---------------------------------------------------

:: 1. Define the installation directory (Standard location)
set "INSTALL_DIR=%USERPROFILE%\.kitoko\bin"

:: 2. Create the directory if it doesn't exist
if not exist "%INSTALL_DIR%" (
    mkdir "%INSTALL_DIR%"
)

:: 3. Copy the compiled executable to the folder
:: Replace 'kitoko-win-x64.exe' with the actual name generated by pkg
if exist "packages\kitoko-cli\kitoko-win-x64.exe" (
    copy "packages\kitoko-cli\kitoko-win-x64.exe" "%INSTALL_DIR%\kitoko.exe" /Y
) else (
    echo Error: Compiled binary not found. Run 'npx pkg .' first.
    pause
    exit /b
)

:: 4. Add to PATH for the current user (if not already there)
echo %PATH% | findstr /C:"%INSTALL_DIR%" >nul
if %errorlevel% neq 0 (
    setx PATH "%PATH%;%INSTALL_DIR%"
    echo Kitoko added to your PATH.
) else (
    echo ℹKitoko is already in your PATH.
)

echo ---------------------------------------------------
echo Installation complete! Restart your terminal.
echo Try typing: kitoko --help
echo ---------------------------------------------------
pause